
import {
  colorCorrectAction,
  restorePhotoAction,
  removeBackgroundAction,
  studioEnhanceAction,
  colorizePhotoAction,
  pictureWithCelebrityAction,
  createYoutubeThumbnailAction,
  autoCaptionsAction,
  aiFutureSelfAction,
  magicInteriorAction,
} from '@/app/actions';
import type { Feature } from '@/lib/types';
import { Wand2, Scissors, Camera, Palette, Image, Type, Hash, Scan, File, StickyNote, PenTool, Braces, LayoutTemplate, Calendar, Users, Briefcase, Sparkles, Home, User, Bot, Wallet, Video, Star, MapPin, Sofa } from 'lucide-react';

const placeholderAction = async (...args: any[]): Promise<any> => {
  console.log('Placeholder action called for a feature in development.');
  // To prevent crashes, we must ensure this function can accept any arguments.
  return { enhancedPhotoDataUri: '', creditCost: 1 };
};

export const featureCategories = {
  IMAGE_STUDIO: 'Image Studio',
  CONTENT_BRAND: 'Content & Brand',
  SMART_OFFICE: 'Smart Office',
  PERSONAL_MAGIC: 'Personal Magic',
  PREMIUM: 'Premium',
};

export const features: Feature[] = [
  // Image Studio
  {
    name: 'Photo Enhancement',
    description: 'One-click color correction & photo restoration.',
    path: '/dashboard/enhance',
    icon: Wand2,
    creditCost: 1,
    // This action is a placeholder as the page now has two separate actions.
    action: placeholderAction,
    showBeforeAfterSlider: true,
    category: featureCategories.IMAGE_STUDIO,
    outputType: 'image',
  },
  {
    name: 'Background Removal',
    description: 'Transparent PNGs in seconds.',
    path: '/dashboard/background-removal',
    icon: Scissors,
    creditCost: 1,
    action: removeBackgroundAction,
    showBeforeAfterSlider: false,
    category: featureCategories.IMAGE_STUDIO,
    outputType: 'image',
  },
  {
    name: 'Photo Studio',
    description: 'Turn product shots into cinematic ads.',
    path: '/dashboard/studio',
    icon: Camera,
    creditCost: 1,
    action: studioEnhanceAction,
    showBeforeAfterSlider: false,
    category: featureCategories.IMAGE_STUDIO,
    outputType: 'image',
  },
  {
    name: 'Photo Colourize',
    description: 'Revive vintage photos in color.',
    path: '/dashboard/colorize',
    icon: Palette,
    creditCost: 1,
    action: colorizePhotoAction,
    showBeforeAfterSlider: true,
    category: featureCategories.IMAGE_STUDIO,
    outputType: 'image',
  },
   {
    name: 'Picture with Celebrity',
    description: 'Blend with famous personalities.',
    path: '/dashboard/picture-with-celebrity',
    icon: Users,
    creditCost: 2,
    action: pictureWithCelebrityAction,
    showBeforeAfterSlider: false,
    category: featureCategories.IMAGE_STUDIO,
    outputType: 'image',
  },
  
  // Content & Brand
  {
    name: 'YouTube Thumbnail Creator',
    description: 'Catchy thumbnails in seconds.',
    path: '/dashboard/youtube-thumbnail',
    icon: Type,
    creditCost: 2,
    action: createYoutubeThumbnailAction,
    showBeforeAfterSlider: false,
    category: featureCategories.CONTENT_BRAND,
    outputType: 'image',
  },
  {
    name: 'Auto Captions + Hashtags',
    description: 'Perfect caption generator.',
    path: '/dashboard/auto-captions',
    icon: Hash,
    creditCost: 1,
    action: autoCaptionsAction,
    showBeforeAfterSlider: false,
    category: featureCategories.CONTENT_BRAND,
    outputType: 'text',
  },
  {
    name: 'Mockup Generator',
    description: 'Visualize products on objects.',
    path: '/dashboard/mockup-generator',
    icon: LayoutTemplate,
    creditCost: 2,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.CONTENT_BRAND,
    isComingSoon: true,
    outputType: 'image',
  },
  {
    name: 'Festive Post Generator',
    description: 'Personalized festival greetings.',
    path: '/dashboard/festive-post',
    icon: Sparkles,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.CONTENT_BRAND,
    isComingSoon: true,
    outputType: 'image',
  },

  // Smart Office
  {
    name: 'Document Scanner + Enhancer',
    description: 'Scan & clean docs.',
    path: '/dashboard/doc-scanner',
    icon: Scan,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.SMART_OFFICE,
    isComingSoon: true,
    outputType: 'image',
  },
   {
    name: 'Magic Bills',
    description: 'Upload bills → get your monthly spending summary beautifully organized.',
    path: '/dashboard/magic-bills',
    icon: Wallet,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.SMART_OFFICE,
    outputType: 'text',
    isComingSoon: true,
  },
  {
    name: 'PDF Tools',
    description: 'Compress, summarize, translate, extract.',
    path: '/dashboard/pdf-tools',
    icon: File,
    creditCost: 3,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.SMART_OFFICE,
    isComingSoon: true,
    outputType: 'text',
  },
  {
    name: 'Notes Generator',
    description: 'Textbook → summarized notes.',
    path: '/dashboard/notes-generator',
    icon: StickyNote,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.SMART_OFFICE,
    isComingSoon: true,
    outputType: 'text',
  },

  // Personal Magic
  {
    name: 'AI Future Self',
    description: 'See your cinematic future version.',
    path: '/dashboard/future-self',
    icon: User,
    creditCost: 2,
    action: aiFutureSelfAction,
    showBeforeAfterSlider: false,
    category: featureCategories.PERSONAL_MAGIC,
    outputType: 'image',
  },
  {
    name: 'Magic Interior',
    description: 'Redesign your room with AI.',
    path: '/dashboard/magic-interior',
    icon: Sofa,
    creditCost: 3,
    action: magicInteriorAction,
    showBeforeAfterSlider: false,
    category: featureCategories.PERSONAL_MAGIC,
    outputType: 'image',
  },

  // Premium
  {
    name: 'AI Voice Studio',
    description: 'Generate realistic voiceovers.',
    path: '/dashboard/voice-studio',
    icon: Bot,
    creditCost: 5,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.PREMIUM,
    isComingSoon: true,
    outputType: 'text',
  },
  {
    name: 'AI Video Enhancer',
    description: 'Upscale and enhance video quality.',
    path: '/dashboard/video-enhancer',
    icon: Video,
    creditCost: 10,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.PREMIUM,
    isComingSoon: true,
    outputType: 'image',
  },
  {
    name: 'Advanced Ad Generator',
    description: 'Create multi-format ad campaigns.',
    path: '/dashboard/advanced-ads',
    icon: Star,
    creditCost: 10,
    action: placeholderAction,
    showBeforeAfterSlider: false,
    category: featureCategories.PREMIUM,
    isComingSoon: true,
    outputType: 'image',
  },
];
