import {
  enhancePhotoAction,
  removeBackgroundAction,
  studioEnhanceAction,
  colorizePhotoAction,
} from '@/app/actions';
import type { Feature } from '@/lib/types';
import { Wand2, Scissors, Camera, Palette, Image, Type, Hash, Scan, File, StickyNote, PenTool, Braces, LayoutTemplate, Calendar, Users, Briefcase, Sparkles, Home, User, Bot, Wallet } from 'lucide-react';

const placeholderAction = async () => ({ enhancedPhotoDataUri: '' });

export const features: Feature[] = [
  {
    name: 'Photo Enhancement',
    description: 'Fix lighting & sharpen details instantly.',
    path: '/dashboard/enhance',
    icon: Wand2,
    creditCost: 1,
    action: enhancePhotoAction,
    showBeforeAfterSlider: true,
  },
  {
    name: 'Background Removal',
    description: 'Transparent PNGs in seconds.',
    path: '/dashboard/background-removal',
    icon: Scissors,
    creditCost: 1,
    action: removeBackgroundAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Photo Studio',
    description: 'Turn raw product shots into cinematic ads.',
    path: '/dashboard/studio',
    icon: Camera,
    creditCost: 1,
    action: studioEnhanceAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Photo Colourize',
    description: 'Revive vintage photos in color.',
    path: '/dashboard/colorize',
    icon: Palette,
    creditCost: 1,
    action: colorizePhotoAction,
    showBeforeAfterSlider: true,
  },
   {
    name: 'My Creations',
    description: 'View your gallery of generated images.',
    path: '/dashboard/creations',
    icon: Image,
    creditCost: 0,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'YouTube Thumbnail Creator',
    description: 'Catchy thumbnails in seconds.',
    path: '/dashboard/youtube-thumbnail',
    icon: Type,
    creditCost: 2,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Auto Captions + Hashtags',
    description: 'Perfect caption generator.',
    path: '/dashboard/auto-captions',
    icon: Hash,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Document Scanner + Enhancer',
    description: 'Scan & clean docs.',
    path: '/dashboard/doc-scanner',
    icon: Scan,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'PDF Tools',
    description: 'Compress, summarize, translate, extract.',
    path: '/dashboard/pdf-tools',
    icon: File,
    creditCost: 3,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Notes Generator',
    description: 'Textbook → summarized notes.',
    path: '/dashboard/notes-generator',
    icon: StickyNote,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Ad Creative Generator',
    description: 'Product → ready ad poster.',
    path: '/dashboard/ad-creative',
    icon: PenTool,
    creditCost: 3,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Brand Guidelines Generator',
    description: 'Upload logo → full style guide.',
    path: '/dashboard/brand-guidelines',
    icon: Braces,
    creditCost: 5,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Mockup Generator',
    description: 'Visualize products on objects.',
    path: '/dashboard/mockup-generator',
    icon: LayoutTemplate,
    creditCost: 2,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Post Scheduler',
    description: 'Plan & auto-post content.',
    path: '/dashboard/post-scheduler',
    icon: Calendar,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'AI Time Capsule',
    description: 'Store memories for future.',
    path: '/dashboard/time-capsule',
    icon: Briefcase,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Festive Post Generator',
    description: 'Personalized festival greetings.',
    path: '/dashboard/festive-post',
    icon: Sparkles,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'House Budget Simplifier',
    description: 'Auto expense visualizer.',
    path: '/dashboard/budget-simplifier',
    icon: Home,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'Picture with Celebrity',
    description: 'Blend with famous personalities.',
    path: '/dashboard/picture-with-celebrity',
    icon: Users,
    creditCost: 2,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'AI Future Self',
    description: 'See yourself 10 years ahead.',
    path: '/dashboard/future-self',
    icon: User,
    creditCost: 2,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  },
  {
    name: 'AI Bill Reader',
    description: 'Scan bills → breakdown + savings tips.',
    path: '/dashboard/bill-reader',
    icon: Wallet,
    creditCost: 1,
    action: placeholderAction,
    showBeforeAfterSlider: false,
  }
];
